import Content1 from '@/components/Content1'
import Content2 from '@/components/Content2'
import Content3 from '@/components/Content3'
import Main from '@/components/Main'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
      <Content1/>
      <Content2/>
      <Content3/>
    </>
  )
}
